spring:
  application:
    name: be

  profiles:
    include: jwt, local

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

  #  # security logging
  #  org.springframework.security: DEBUG