spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nursey
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true